# Generated by Django 2.1.7 on 2022-10-18 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_avatar_blogs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogs',
            new_name='Blog',
        ),
    ]
