# Generated by Django 2.0 on 2022-09-29 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_borrar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='foto',
        ),
    ]
