# Generated by Django 2.1.7 on 2022-10-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20221019_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='usuario',
            field=models.CharField(default='Some String', max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='cuerpo',
            field=models.TextField(max_length=5000),
        ),
    ]
