# Generated by Django 2.0 on 2022-09-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_blog_foto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='borrar',
        ),
        migrations.AddField(
            model_name='blog',
            name='autor',
            field=models.CharField(default='hol', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='fecha',
            field=models.DateField(default='2022-10-10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='subtitulo',
            field=models.CharField(default='hola', max_length=50),
            preserve_default=False,
        ),
    ]
