# Generated by Django 2.0 on 2022-10-09 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatarborrar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Avatares'),
        ),
    ]
