# Generated by Django 2.0.2 on 2022-10-10 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_remove_avatar_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatarborrar',
            name='blog',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='chat.blog'),
        ),
    ]
