# Generated by Django 2.0.2 on 2022-10-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_avatarborrar_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
        migrations.RemoveField(
            model_name='avatarborrar',
            name='blog',
        ),
        migrations.AddField(
            model_name='blog',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Avatares/'),
        ),
        migrations.DeleteModel(
            name='Avatarborrar',
        ),
    ]
