# Generated by Django 2.0.2 on 2022-10-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_auto_20221011_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='subtitulo',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='blog',
            name='titulo',
            field=models.CharField(max_length=80),
        ),
    ]
